name: Automated tests

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Fetch artifact ID
        id: get-artifact-id
        run: |
          ARTIFACT_ID=$(curl -L -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Dan1lV1t/allure_integration/actions/artifacts?name=allure-results \
            | python3 -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id'])")
          echo "ARTIFACT_ID=${ARTIFACT_ID}" >> $GITHUB_ENV
      - name: Download artifact
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/Dan1lV1t/allure_integration/actions/artifacts/${{ env.ARTIFACT_ID }}/zip" \
            -o artifacts.zip
      - name: Check downloaded artifact
        run: |
          echo "Downloaded artifact details:"
          ls -la artifacts.zip
          file artifacts.zip
      - run: mkdir allure-results && unzip artifacts.zip -d allure-results
      - name: List contents of allure-results
        run: ls -la allure-results
      - name: Store allure history
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: download-history

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download allure results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results
      - name: Run test
        run: pytest --alluredir=allure-results
      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz && sudo tar -zxvf allure-2.23.





